services:
  flask:
    container_name: flask
    build: .
    command: poetry run python app/main.py
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "5000:5000"


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: